### ISSUE TITLE
Huge pages Q&A

### ISSUE THREAD

**Issue by hyperbolic2346** [charmed-kubernetes/kubernetes-docs#278]
Q: How do I use hugepages in my pods on Charmed Kubernetes?
A: First, enable huge pages on the nodes. Check the current sysctl settings and add to them. Default settings would be:
```juju config kubernetes-workers sysctl="{ net.ipv4.conf.all.forwarding : 1, net.ipv4.neigh.default.gc_thresh1: 128, net.ipv4.neigh.default.gc_thresh2 : 28672, net.ipv4.neigh.default.gc_thresh3: 32768, net.ipv6.neigh.default.gc_thresh1 : 128, net.ipv6.neigh.default.gc_thresh2: 28672, net.ipv6.neigh.default.gc_thresh3 : 32768, fs.inotify.max_user_instances: 8192, fs.inotify.max_user_watches: 1048576, vm.nr_hugepages: 100 }"```

Change the 100 huge pages to the number of 2 Mi pages needed.

Then add pods that need hugepages such as:
```
apiVersion: v1
kind: Pod
metadata:
  name: hugepages-test
spec:
  containers:
  - image: ubuntu:latest
    command:
    - sleep
    - inf
    name: example
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    resources:
      limits:
        hugepages-2Mi: 100Mi
        memory: 100Mi
      requests:
        memory: 100Mi      
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
```

To verify huge pages, you can exec into the pod and check /proc/meminfo `kubectl exec hugepage-test cat /proc/meminfo | grep HugePages_`.
