### ISSUE TITLE
Add Ceph overlay to docs

### ISSUE THREAD

**Issue by tvansteenburgh** [charmed-kubernetes/kubernetes-docs#280]
We should add an overlay for the instructions at https://ubuntu.com/kubernetes/docs/storage

**Comment by knkski** [comment]
This is the overlay that I am using based on the existing docs commands:

```yaml
applications:
  ceph-mon:
    charm: cs:ceph-mon
    scale: 3
  ceph-osd:
    charm: cs:ceph-osd
    scale: 3
    storage:
      osd-devices: 32G,2
      osd-journals: 8G,1
relations:
  - [ceph-mon, ceph-osd]
  - [ceph-mon:admin, kubernetes-master]
  - [ceph-mon:client, kubernetes-master]
```
