### ISSUE TITLE
"OpenStack integration - API Server Load Balancer" example uses deprecated relation

### ISSUE THREAD

**Issue by nobuto-m** [charmed-kubernetes/kubernetes-docs#653]
In the "API Server Load Balancer" section, there is an example of the overly bundle.
https://ubuntu.com/kubernetes/docs/openstack-integration#api-server-load-balancer
```
  - ["openstack-integrator", "kubernetes-master:loadbalancer"]
  - ["openstack-integrator", "kubernetes-master:openstack"]
  - ["openstack-integrator", "kubernetes-worker:openstack"]
```

However, the `loadbalancer` relation is discouraged nowadays and it would be nice if it's updated to the new method based on:
https://github.com/charmed-kubernetes/charm-kubernetes-control-plane/commit/a69a6c19d42feed0488789d3dd334f3a6bb52622

[metadata.yaml]
```
  loadbalancer:
    # Use of this relation is strongly discouraged in favor of the more
    # explicit loadbalancer-internal / loadbalancer-external relations.
    interface: public-address
...
  loadbalancer-internal:
    # Indicates that the LB should not be public and should use internal
    # networks if available. Intended for control plane and other internal use.
    interface: loadbalancer
  loadbalancer-external:
    # Indicates that the LB should be public facing. Intended for clients which
    # must reach the API server via external networks.
    interface: loadbalancer
```
