### ISSUE TITLE
On Kubernetes 1.25 deploying the aws-integrator plugin will not handle the CSI ebs provisioner

### ISSUE THREAD

**Issue by dickeyf** [charmed-kubernetes/kubernetes-docs#731]
Kubernetes 1.25 seems to force me in using the csi provisioner in AWS;

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    juju.io/workload-storage: "true"
  labels:
    cdk-addons: "true"
  name: cdk-ebs
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

For example, the above StorageClass is what aws-integrator will create.  When I use it, PVCs are stuck in Pending:
```
  Normal  ExternalProvisioning  7s (x6 over 64s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```

I believe this is because the in-tree EBS provisioner `kubernetes.io/aws-ebs` that the `aws-integrator` is using is now deprecated and the PVC is force to use `ebs.csi.aws.com` instead.

`aws-integrator` will need to also deploy the new AWS CSI driver in order to allow EBS creations.
